- id: '1600604398275'
  alias: Approaching home
  description: ''
  trigger:
  - platform: state
    entity_id: person.jessica_pawlowski
    to: 'home'
    from: 'not_home'
  condition:
  - condition: state
    entity_id: person.james_doig
    state: 'home'
  action:
  - service: tts.google_say
    data:
      entity_id: all
      message: Jess approaching home
  mode: single
