
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


homeassistant:
  external_url: https://home.doig.uk
#   whitelist_external_dirs:
#    - '/home/pi/.homeassistant/camera'
#  media_dirs:
#    music: /home/pi/mnt/gdrive/Music
#    tts: /home/pi/.homeassistant/www/tts

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
#     swag container 
    - 172.19.0.2 
    - 127.0.0.1

#  ssl_certificate: /ssl/letsencrypt/live/home.doig.uk/fullchain.pem
#  ssl_key: /ssl/letsencrypt/live/home.doig.uk/privkey.pem


influxdb:
  host: 172.19.0.9
  port: 8086
  ssl: false
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  include:
    domains:
      - light
      - binary_sensor
      - sensor
      - person

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    base_url: https://home.doig.uk
    cache_dir: /config/www/tts

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: YAML
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace.yaml


system_health:

yeelight:
  devices:
    192.168.1.84:
      name: Nurserylight
      model: ceiling3

plex_assistant:
  url: 'http://192.168.1.5:32400'
  token: !secret plex_token
  default_cast: 'TV'
  language: 'en'
  tts_errors: true

webostv:
  host: 192.168.1.95
  name: TV
  turn_on_action:
    service: persistent_notification.create
    data:
      message: "Turn on action"
  customize:
    sources:
      - youtube

badnest:
  user_id: !secret nest_user
  accesstoken:  !secret nest_token
  region: eu

climate:
  - platform: badnest
    scan_interval: 10

sensor:
  - platform: cert_expiry
    host: home.doig.uk

  - platform: badnest

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: attributes
    friendly_name: "Boiler"
    attribute: hvac_action
    unit_of_measurement: ""
    entities:
      - climate.hallway_thermostat

  - platform: plex_assistant

  - platform: template
    sensors:
     hvac_action:
        value_template: >
          {% set mapper =
            { 'idle':'0',
              'heating':'100'} %}   
          {% set state = states('sensor.hallway_thermostat_hvac_action') %}
          {% set id = mapper[state] if state in mapper %}
          {{ id }}

     unifi_wanip:
       friendly_name: "WAN IP address"
       unit_of_measurement: ''
       value_template: "{{ state_attr('sensor.unifi_gateway_wan', 'wan_ip') }}"

  - platform: unifigateway
    host: 192.168.1.1
    username: !secret unifi_user
    password: !secret unifi_password
    monitored_conditions:
      - www
      - wan
      - lan
      - wlan

logger:
  default: info
  logs:
    custom_components.xiaomi_gateway3: debug


recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 5
  exclude:
    domains:
      - unifi

google_assistant:
  project_id: hale-trilogy-289723
  service_account: !include HAgoogleassistant-a74a22e861d3.json
  report_state: true
  exposed_domains:
    - light
  entity_config:
    light.yeelight:
      name: Lighty
    
