# Home Assistant configuration
# source: doig007/HomeAssistant-Config

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


homeassistant:
  external_url: https://home.doig.uk
#   whitelist_external_dirs:
#    - './camera'
#  media_dirs:
#    music: /home/pi/mnt/gdrive/Music

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
#     swag container 
    - 172.19.0.2 
    - 127.0.0.1

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    base_url: https://home.doig.uk
    cache_dir: /config/www/tts

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info
  logs:
    custom_components:unifigateway: debug
#    recorder: debug

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 5
  exclude:
    domains:
      - unifi

discovery:
  ignore:
    - yeelight

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: YAML
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace.yaml
  # References to front-end custom cards from HACS (n.b. does not work in storage mode)
  resources:
    - url: /local/circle-sensor-card.js?v=0
      type: module
    - url: /local/custom-lovelace/home-feed-card/lovelace-home-feed-card.js?v=0.0.0
      type: js
    - url: /local/mini-media-player-bundle.js?v=1.11.0
      type: module
    - url: /local/flex-table-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /local/simple-thermostat.js?v=1
      type: module
    - url: /local/mini-graph-card-bundle.js?v=0.9.4
      type: module


system_health:

notify:

media_player:

# Use light group rather than groups.yaml to enable brightness control
light: !include lights.yaml

# Explicit declaration of yeelight since discovery is imperfect
yeelight:
  devices:
    192.168.1.84:
      name: Nurserylight
      model: ceiling3
      
# Xiaomi air purifier      
fan:
  - platform: xiaomi_miio
    host: 192.168.1.120
    token: !secret fan_token    
          
# Custom component used to access Nest API
badnest:
  user_id: !secret nest_user
  accesstoken: !secret nest_token
  region: eu

# Set up climate entity for badnest custom component
climate:
  - platform: badnest
    scan_interval: 10
    
# Custom component used for voice control of various HA entities.  Uses personal google service
google_assistant:
  project_id: hale-trilogy-289723
  service_account: !include HAgoogleassistant-a74a22e861d3.json
  report_state: true
  exposed_domains:
    - light
    - group
    - script
    - sensor
  entity_config:
    group.lights_livingroom:
      name: Prepare the drawing room

# Custom component used for voice control of plex
plex_assistant:
  url: 'http://192.168.1.5:32400'
  token: !secret plex_token
  default_cast: 'TV'
  language: 'en'
  tts_errors: true

# LG integration conf with fixed IP of TV
webostv:
  host: 192.168.1.167
  name: TV
  turn_on_action:
    service: persistent_notification.create
    data:
      message: "Turn on action"
  customize:
    sources:
      - youtube

# Declaration of various sensors
sensor:
  - platform: cert_expiry
    host: home.doig.uk

  - platform: badnest

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: attributes
    friendly_name: "Boiler"
    attribute: hvac_action
    unit_of_measurement: ""
    entities:
      - climate.hallway_thermostat

  - platform: plex_assistant

  - platform: template
    sensors:
     hvac_action:
        value_template: >
          {% set mapper =
            { 'idle':'0',
              'heating':'100'} %}   
          {% set state = states('sensor.hallway_thermostat_hvac_action') %}
          {% set id = mapper[state] if state in mapper %}
          {{ id }}
     average_aqi:
        value_template: >
          {{ state_attr('fan.xiaomi_miio_device', 'average_aqi') }}

     unifi_wanip:
       friendly_name: "WAN IP address"
       unit_of_measurement: ''
       value_template: "{{ state_attr('sensor.unifi_gateway_wan', 'wan_ip') }}"

  - platform: unifigateway
    host: 192.168.1.1
    username: !secret unifi_user
    password: !secret unifi_password
    verify_ssl: False
    monitored_conditions:
      - www
      - wan
      - lan
      - wlan

influxdb:
  host: 172.19.0.9
  port: 8086
  ssl: false
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  include:
    domains:
      - light
      - binary_sensor
      - sensor
      - person
      - climate
      - fan
  exclude:
    entities:
      - sun.sun
      - script.blink_take_photo
      - sensor.cert_expiry_home_doig_uk
      - sensor.cert_expiry_timestamp_home_doig_uk
      - sensor.hampstead_probability_of_precipitation
      - sensor.hampstead_weather
      - sensor.hampstead_wind_speed

