title: Yaml dashboard
views:
  - path: default_view
    title: Home
    panel: true
    badges: null
    cards:
      - type: picture-elements
        image: ../local/floorplan.png
        elements:
          - entity: binary_sensor.yeelight_nightlight
            style:
              left: 40%
              top: 25%
            type: state-badge

      - type: picture-elements
        image: ../local/james.gif
        elements:
              - entity: sensor.oneplus_a5000_battery_level
                type: custom:circle-sensor-card
                max: 100
                min: 0
                stroke_width: 2
                gradient: true
                units: '%'
                font_style:
                  color: red
                  font-size: 1.0em
                  font-family: 'Trebuchet MS'
                color_stops:
                  18: '#55FF55'
                  20: '#5555FF'
                  24: '#FF5555'
                style:
                  top: 80%
                  left: 20%
                  width: 25px
                  height: 25px
              - entity: person.james_doig
                style:
                  left: 50%
                  top: 10%
                type: state-label

      - type: picture-elements
        image: ../local/jess.gif
        elements:
              - entity: sensor.lya_l09_battery_level
                style:
                  left: 20%
                  top: 90%
                type: state-badge
            




